version: "3"

services:
  php-apache:
    build:
      context: .
      # dockerfile: Dockerfile
      args:
        uid: ${UID}
    container_name: php-apache
    ports:
      - "8000:80"
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    volumes:
      - .:/var/www/html
    networks:
      - laravel

  mysql:
    image: mysql:5.7.22
    container_name: mysql
    # restart: unless-stopped
    # tty: true
    # ports:
    #   - "3306:3306"
    volumes:
      - .docker/dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: secretrootpassword
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  # nginx:
  #   image: nginx:stable-alpine
  #   container_name: nginx
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./src:/var/www
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - php
  #     - mysql
  #   networks:
  #     - laravel

networks:
  laravel:
    driver: bridge
